### ISSUE TITLE
DocNorms: Creating a WD, TOC creation tools

### ISSUE THREAD

**Issue by davaya** [oasis-tcs/openc2-tc-ops#36]
Documentation Norms Section 4.4.1 says that pandoc can be used to generate a markdown table of contents.  Although pandoc will do that (and much more), installing it solely for the purpose of generating a TOC is overkill.  There are millions of markdown TOC generator plugins for various editors and we can't mention them all, but it would be useful to note that that editor plugins are a lightweight alternative.

For vscode I'm using [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one), (which has 1.8 million installs and 5 star reviews).

Generating and previewing the TOC directly in an editor is very convenient, and deserves a mention in Norms.

**Comment by dlemire60** [comment]
Edited issue title to be more descriptive.  

`pandoc` was a tool we identified and made extensive use of when the TC first moved to markdown for work products, and the current Doc Norms content captures useful experience with that tool. I'm happy to capture additional resources in the tools section, and possibly move specific guidance for using `pandoc` to an appendix.

Thanks for the suggestion of the VSCode plug-in.
