### ISSUE TITLE
GitHub Maintainers

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-tc-ops#51]
Documentation norms should have something about github maintainers. Include: 

- how OASIS staff retains admin rights for whatever it is they can do that we can't
- that maintainers are assigned based on TC role and cochairs, secretary, and work product editors all become maintainers by definition
- actually giving the maintainer role is one of the OASIS staff functions (ie only staff can actually update github to add or delete a maintainer)
- reference https://www.oasis-open.org/maintainers-guide/ for the OASIS guide for maintainers
- the repo should contain the names of the maintainers in the readme and/or contributing file

**Comment by dlemire60** [comment]
I have very recently had similar thoughts, but your list of items to address is more thorough. Now on the to-do list.

**Comment by dlemire60** [comment]
The link @sparrell provided is actually guidance for maintainers of OASIS _open_ repositories, not TC repos. I don't see any specific guidance for the latter on the OASIS website, nor in the 4-part guidance for editors. So I think we just need to craft some words of our own.

**Comment by dlemire60** [comment]
Addressed by PR #52 . Closing
